image: Visual Studio 2017

version: 0.0.{build}

branches:
  # whitelist
  only:
    - master
    - test-build

clone_depth: 1

before_build:
  - nuget restore

test_script:
  - nunit3-console  --result=results.xml;format=AppVeyor