image: Visual Studio 2017

version: 0.2.{build}

platform:
  - 'Any CPU'

configuration: Release

branches:
  # whitelist
  only:
    - master
    - test-build

clone_depth: 1

before_build:
  - nuget restore

test:
  assemblies:
    - '**\bin\$(configuration)\TinyECSTests.dll'

artifacts:
    - path: TinyECS.zip

after_build:
  #create zip archive with all the binaries and documentation
  7z a TinyECS.zip %APPVEYOR_BUILD_FOLDER%\TinyECS\bin\%CONFIGURATION%\*.dll %APPVEYOR_BUILD_FOLDER%\README.md %APPVEYOR_BUILD_FOLDER%\LICENSE %APPVEYOR_BUILD_FOLDER%\TinyECSUnityIntegration\bin\%CONFIGURATION%\TinyECSUnityIntegration.dll

skip_tags: true

deploy:
  release: TinyECS-v$(appveyor_build_version)
  description: ''
  provider: GitHub
  auth_token:
    secure: 1xPR+/5vbL2PEPkG/LtjPXkZqAfB6vZWxVrUCdr6afKZ9utwUA7n6mzDv7//N2gk
  artifact: /.*\.zip/            
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only